---
- hosts: server-production
  become: true
  tasks:
    - name: Copy WAR to webapps
      copy: src=../../greetings-app/target/greetings-0.1-RELEASE.war dest=/opt/tomcat/webapps/hello.war owner=vagrant group=vagrant mode=0744
